"""core 模块 —— 领域类型与异常。"""

from core.exceptions import (
    ArmError,
    CameraError,
    DetectionFailedError,
    DropLimitExceededError,
    HardwareError,
    InspectionReadError,
    InspectionTimeoutError,
    MissionError,
    NavigationBlockedError,
    NavigationLostError,
    ObstacleBlockedError,
    ObstacleTimeoutError,
    PerceptionError,
    PickupFailedError,
    SpeakerError,
    ZoneOCRError,
)
from core.types import (
    VALID_ZONES,
    ArmPose,
    BBox,
    CameraIntrinsics,
    ConeDetection,
    EquipmentDetection,
    InspectionReading,
    JointAngles,
    MeterStatus,
    MissionPhase,
    NavigationStatus,
    PickupOutcome,
    Point3D,
    RobotPose,
    StripDetection,
    Zone,
)

__all__ = [
    # enums
    "Zone",
    "MeterStatus",
    "MissionPhase",
    "PickupOutcome",
    "NavigationStatus",
    # structs
    "BBox",
    "InspectionReading",
    "ConeDetection",
    "EquipmentDetection",
    "StripDetection",
    "RobotPose",
    "ArmPose",
    "JointAngles",
    "CameraIntrinsics",
    "Point3D",
    # constants
    "VALID_ZONES",
    # exceptions
    "MissionError",
    "ObstacleTimeoutError",
    "ObstacleBlockedError",
    "InspectionTimeoutError",
    "InspectionReadError",
    "ZoneOCRError",
    "PickupFailedError",
    "DropLimitExceededError",
    "ArmError",
    "NavigationLostError",
    "NavigationBlockedError",
    "PerceptionError",
    "DetectionFailedError",
    "HardwareError",
    "CameraError",
    "SpeakerError",
]
